---
layout: post
title: Introduction to Promise
subtitle: Standard built-in objects
date: 2019-04-17
author: Jalever
header-img: img/post-bg-js-version.jpg
catalog: true
tags:
  - JavaScript
---
- [Overview](#overview)
- [Syntax](#syntax)
    - [Parameters](#parameters)
- [Description](#description)
- [Properties](#properties)
    - [Promise.length](#promiselength)
    - [Promise.prototype](#promiseprototype)
- [Methods](#methods)
    - [Promise.all(iterable)](#promisealliterable)
    - [Promise.allSettled()](#promiseallSettled)
    - [Promise.race(iterable)](#promiseraceiterable)
    - [Promise.reject()](#promisereject)
    - [Promise.resolve()](#promiseresolve)
- [Promise prototype](#promise-prototype)
    - [Properties](#properties)
        - [Promise.prototype.constructor](#promiseprototypeconstructor)
    - [Methods](#methods)
        - [Promise.prototype.catch()](#promiseprototypecatch)
        - [Promise.prototype.then()](#promiseprototypethen)
        - [Promise.prototype.finally()](#promiseprototypefinally)
- [Create a Promise](#create-a-promise)    
- [Examples](#examples)
    - [Basic Example](#basic-example)

## Overview
The Promise object represents the eventual completion (or failure) of an asynchronous operation, and its resulting value.
![e9Clin.png](https://s2.ax1x.com/2019/07/21/e9Clin.png)

## Syntax
![e9CBJ1.png](https://s2.ax1x.com/2019/07/21/e9CBJ1.png)

#### Parameters
&nbsp;&nbsp;<strong>executor</strong><br/>
&nbsp;&nbsp;A function that is passed with the arguments `resolve` and `reject`. The `executor` function is executed immediately by the Promise implementation, passing `resolve` and `reject` functions (the executor is called before the `Promise` constructor even returns the created object). The `resolve` and `reject` functions, when called, resolve or reject the promise, respectively. The executor normally initiates some asynchronous work, and then, once that completes, either calls the `resolve` function to resolve the promise or else `rejects` it if an error occurred. If an error is thrown in the executor function, the promise is rejected. The return value of the executor is ignored.

## Description
A `Promise` is a proxy for a value not necessarily known when the promise is created. It allows you to associate handlers with an asynchronous action's eventual success value or failure reason. This lets asynchronous methods return values like synchronous methods: instead of immediately returning the final value, the asynchronous method returns a <i>Promise</i> to supply the value at some point in the future.

A `Promise` is in one of these states:
- <strong>pending</strong>: initial state, neither fulfilled nor rejected.
- <strong>fulfilled</strong>: meaning that the operation completed successfully.
- <strong>rejected</strong>: meaning that the operation failed.

A pending promise can either be <strong>fulfilled</strong> with a value, or <strong>rejected</strong> with a reason (error). When either of these options happens, the associated handlers queued up by a promise's `then` method are called. (If the promise has already been fulfilled or rejected when a corresponding handler is attached, the handler will be called, so there is no race condition between an asynchronous operation completing and its handlers being attached.)

As the <strong>Promise.prototype.then()</strong> and <strong>Promise.prototype.catch()</strong> methods return promises, they can be chained.
![e9AWG9.png](https://s2.ax1x.com/2019/07/21/e9AWG9.png)
> A Promise is said to be settled if it is either `fulfilled` or `rejected`, but not pending. You will also hear the term `resolved` used with promises — this means that the promise is settled or “locked in” to match the state of another promise.

## Properties
#### Promise.length
Length property whose value is always 1 (number of constructor arguments).

#### Promise.prototype  
The `Promise.prototype` property represents the prototype for the `Promise` constructor.

`Promise` instances inherit from `Promise.prototype`. You can use the constructor's prototype object to add properties or methods to all `Promise` instances.

<table>
    <thead>
        <tr>
            <td colspan="3">Property attributes of Promise.prototype</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Writable</td>
            <td>no</td>
        </tr>
        <tr>
            <td>Enumerable</td>
            <td>no</td>
        </tr>
        <tr>
            <td>Configurable</td>
            <td>no</td>
        </tr>
    </tbody>
</table>

## Methods
#### Promise.all(iterable)
The `Promise.all()` method returns a single `Promise` that resolves when all of the promises passed as an iterable have resolved or when the iterable contains no promises. It rejects with the reason of the first promise that rejects.
![e9JkYn.png](https://s2.ax1x.com/2019/07/21/e9JkYn.png)

###### Syntax
![e9J0kd.png](https://s2.ax1x.com/2019/07/21/e9J0kd.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>iterable</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An iterable object such as an Array.<br/>
&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;- An <strong>already resolved</strong> `Promise` if the iterable passed is empty.<br/>
&nbsp;&nbsp;&nbsp;&nbsp;- An <strong>asynchronously resolved</strong> `Promise` if the iterable passed contains no promises. Note, Google Chrome 58 returns an <strong>already resolved</strong> promise in this case.<br/>
&nbsp;&nbsp;&nbsp;&nbsp;- A <strong>pending</strong> `Promise` in all other cases. This returned promise is then resolved/rejected <strong>asynchronously</strong> (as soon as the stack is empty) when all the promises in the given iterable have resolved, or if any of the promises reject. See the example about "Asynchronicity or synchronicity of Promise.all" below. Returned values will be in order of the Promises passed, regardless of completion order.

###### Description
This method can be useful for aggregating the results of multiple promises.

&nbsp;&nbsp;<strong>Fulfillment</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;The returned promise is fulfilled with an array containing all the values of the <i>iterable</i> passed as argument (also non-promise values).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- If an empty <i>iterable</i> is passed, then this method returns (synchronously) an already resolved promise.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- If all of the passed-in promises fulfill, or are not promises, the promise returned by <strong>Promise.all</strong> is fulfilled asynchronously.

&nbsp;&nbsp;<strong>Rejection</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;If any of the passed-in promises reject, <strong>Promise.all</strong> asynchronously rejects with the value of the promise that rejected, whether or not the other promises have resolved.

###### Examples
<strong>Using Promise.all</strong><br/>
Promise.all waits for all fulfillments (or the first rejection).
![e9UGUe.png](https://s2.ax1x.com/2019/07/21/e9UGUe.png)
If the <ins>iterable</ins> contains non-promise values, they will be ignored, but still counted in the returned promise array value (if the promise is fulfilled):
![e9Ug8s.png](https://s2.ax1x.com/2019/07/21/e9Ug8s.png)
![e9UfK0.png](https://s2.ax1x.com/2019/07/21/e9UfK0.png)

<strong>Asynchronicity or synchronicity of Promise.all</strong><br/>
This following example demonstrates the asynchronicity (or synchronicity, if the iterable passed is empty) of <strong>Promise.all</strong>:
![e9dkY4.png](https://s2.ax1x.com/2019/07/21/e9dkY4.png)

The same thing happens if <strong>Promise.all</strong> rejects:
![e9wEE8.png](https://s2.ax1x.com/2019/07/21/e9wEE8.png)

But, <strong>Promise.all</strong> resolves synchronously <ins>if and only if</ins> the <i>iterable</i> passed is empty:
![e90nIO.png](https://s2.ax1x.com/2019/07/21/e90nIO.png)

<strong>Promise.all fail-fast behaviour</strong><br/>
<strong>Promise.all</strong> is rejected if any of the elements are rejected. For example, if you pass in four promises that resolve after a timeout and one promise that rejects immediately, then <strong>Promise.all</strong> will reject immediately.
![e90vSH.png](https://s2.ax1x.com/2019/07/21/e90vSH.png)
![e9BSOI.png](https://s2.ax1x.com/2019/07/21/e9BSOI.png)
It is possible to change this behaviour by handling possible rejections:
![e90IyR.png](https://s2.ax1x.com/2019/07/21/e90IyR.png)

#### Promise.allSettled()
The <strong>Promise.allSettled()</strong> method returns a promise that resolves after all of the given promises have either resolved or rejected, with an array of objects that each describe the outcome of each promise.
![e94Rzt.png](https://s2.ax1x.com/2019/07/21/e94Rzt.png)

###### Syntax
![e94ToQ.png](https://s2.ax1x.com/2019/07/21/e94ToQ.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>iterable</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An iterable object, such as an Array, in which each member is a Promise.<br/>
&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;A <strong>pending</strong> `Promise` that will be <strong>asynchronously</strong> fulfilled once every promise in the specified collection of promises has completed, either by successfully being fulfilled or by being rejected. At that time, the returned promise's handler is passed as input an array containing the outcome of each promise in the original set of promises.<br/>

#### Promise.race(iterable)
The <strong>Promise.race()</strong> method returns a promise that fulfills or rejects as soon as one of the promises in an iterable fulfills or rejects, with the value or reason from that promise.
![e953lt.png](https://s2.ax1x.com/2019/07/21/e953lt.png)

###### Syntax
![e9Iecq.png](https://s2.ax1x.com/2019/07/21/e9Iecq.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>iterable</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An iterable object, such as an <strong>Array</strong>.<br/>
&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;A <strong>pending</strong> `Promise` that <strong>asynchronously</strong> yields the value of the first promise in the given iterable to fulfill or reject.<br/>

###### Description
The <strong>race</strong> function returns a <strong>Promise</strong> that is settled the same way (and takes the same value) as the first promise that settles amongst the promises of the iterable passed as an argument.

If the iterable passed is empty, the promise returned will be forever pending.

If the iterable contains one or more non-promise value and/or an already settled promise, then <strong>Promise.race</strong> will resolve to the first of these values found in the iterable.

###### Examples
<strong>Asynchronicity of Promise.race</strong><br/>
This following example demonstrates the asynchronicity of `Promise.race`:
![e9ouRA.png](https://s2.ax1x.com/2019/07/21/e9ouRA.png)
An empty iterable causes the returned promise to be forever pending:
![e9oQMt.png](https://s2.ax1x.com/2019/07/21/e9oQMt.png)
If the iterable contains one or more non-promise value and/or an already settled promise, then `Promise.race` will resolve to the first of these values found in the array:
![e9otiQ.png](https://s2.ax1x.com/2019/07/21/e9otiQ.png)

<strong>Using Promise.race – examples with setTimeout</strong><br/>
![e9oci4.png](https://s2.ax1x.com/2019/07/21/e9oci4.png)
![e9ofQ1.png](https://s2.ax1x.com/2019/07/21/e9ofQ1.png)
![e9o4L6.png](https://s2.ax1x.com/2019/07/21/e9o4L6.png)

#### Promise.reject()
The Promise.reject() method returns a Promise object that is rejected with a given reason.
![e9T861.png](https://s2.ax1x.com/2019/07/21/e9T861.png)

###### Syntax
![e9Tt0K.png](https://s2.ax1x.com/2019/07/21/e9Tt0K.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>reason</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reason why this <strong>Promise</strong> rejected.<br/>
&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;A <strong>Promise</strong> that is rejected with the given reason.<br/>

###### Description
The static <strong>Promise.reject</strong> function returns a <strong>Promise</strong> that is rejected. For debugging purposes and selective error catching, it is useful to make <strong>reason</strong> an <strong>instanceof</strong> <strong>Error</strong>.

###### Examples
<strong>Using the static Promise.reject() method</strong><br/>
![e9ToXq.png](https://s2.ax1x.com/2019/07/21/e9ToXq.png)

#### Promise.resolve()
The <strong>Promise.resolve()</strong> method returns a <strong>Promise</strong> object that is resolved with a given value. If the value is a promise, that promise is returned; if the value is a thenable (i.e. has a "then" method), the returned promise will "follow" that thenable, adopting its eventual state; otherwise the returned promise will be fulfilled with the value. This function flattens nested layers of promise-like objects (e.g. a promise that resolves to a promise that resolves to something) into a single layer.
> Do not call `Promise.resolve` on a thenable that resolves to itself. This will cause infinite recursion as it tries to flatten what seems to be an infinitely nested promise.
![e9q34O.png](https://s2.ax1x.com/2019/07/21/e9q34O.png)

###### Syntax
![e9qUKA.png](https://s2.ax1x.com/2019/07/21/e9qUKA.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Argument to be resolved by this <strong>Promise</strong>. Can also be a <strong>Promise</strong> or a thenable to resolve.<br/>
&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;A Promise that is resolved with the given value, or the promise passed as value, if the value was a promise object.<br/>

###### Description
The static <strong>Promise.resolve</strong> function returns a <strong>Promise</strong> that is resolved.

###### Examples
<strong>Using the static Promise.resolve method</strong><br/>
![e9O86H.png](https://s2.ax1x.com/2019/07/21/e9O86H.png)

<strong>Resolving an array</strong><br/>
![e9OHBR.png](https://s2.ax1x.com/2019/07/21/e9OHBR.png)

<strong>Resolving another Promise</strong><br/>
![e9XmvQ.png](https://s2.ax1x.com/2019/07/21/e9XmvQ.png)
The inverted order of the logs is due to the fact that the <strong>then</strong> handlers are called asynchronously.

<strong>Resolving thenables and throwing Errors</strong><br/>
![e9X7RS.png](https://s2.ax1x.com/2019/07/21/e9X7RS.png)
![e9Xvaq.png](https://s2.ax1x.com/2019/07/21/e9Xvaq.png)
![e9XxI0.png](https://s2.ax1x.com/2019/07/21/e9XxI0.png)

## Promise prototype
#### Properties
###### Promise.prototype.constructor
Returns the function that created an instance's prototype. This is the <strong>Promise</strong> function by default.

#### Methods
###### Promise.prototype.catch()
The <strong>catch()</strong> method returns a <strong>Promise</strong> and deals with rejected cases only. It behaves the same as calling <strong>Promise.prototype.then(undefined, onRejected)</strong> (in fact, calling <strong>obj.catch(onRejected)</strong> internally calls <strong>obj.then(undefined, onRejected))</strong>. This means that you have to provide an <strong>onRejected</strong> function even if you want to fall back to an <strong>undefined</strong> result value - for example <strong>obj.catch(() => {})</strong>.
![e9j1Ld.png](https://s2.ax1x.com/2019/07/21/e9j1Ld.png)

<strong>Syntax</strong><br/>
![e9jswn.png](https://s2.ax1x.com/2019/07/21/e9jswn.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>onRejected</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A <strong>Function</strong> called when the <strong>Promise</strong> is rejected. This function has one argument:<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>reason</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The rejection reason.<br/>

&nbsp;&nbsp;<strong>Return value</strong><br/>
Internally calls <strong>Promise.prototype.then</strong> on the object upon which it was called, passing the parameters <strong>undefined</strong> and the received <strong>onRejected</strong> handler. Returns the value of that call, which is a <strong>Promise</strong>.

The Promise returned by <strong>catch()</strong> is rejected if <strong>onRejected</strong> throws an error or returns a Promise which is itself rejected; otherwise, it is resolved.

<strong>Description</strong><br/>
The <strong>catch</strong> method is used for error handling in promise composition. Since it returns a <strong>Promise</strong>, it can be chained in the same way as its sister method, <strong>then()</strong>.

<strong>Examples</strong><br/>
&nbsp;&nbsp;<strong>Using and chaining the catch method</strong><br/>
![e9x62T.png](https://s2.ax1x.com/2019/07/21/e9x62T.png)

&nbsp;&nbsp;<strong>Gotchas when throwing errors</strong><br/>
![e9xoPx.png](https://s2.ax1x.com/2019/07/21/e9xoPx.png)
![e9xTG6.png](https://s2.ax1x.com/2019/07/21/e9xTG6.png)
![e9x7RK.png](https://s2.ax1x.com/2019/07/21/e9x7RK.png)

&nbsp;&nbsp;<strong>If it is resolved</strong><br/>
![e9xvdA.png](https://s2.ax1x.com/2019/07/21/e9xvdA.png)

###### Promise.prototype.then()
The <strong>then()</strong> method returns a <strong>Promise</strong>. It takes up to two arguments: callback functions for the success and failure cases of the <strong>Promise</strong>.
![eC91OS.png](https://s2.ax1x.com/2019/07/21/eC91OS.png)
> If one or both arguments are omitted or are provided non-functions, then `then` will be missing the handler(s), but will not generate any errors. If the `Promise` that `then` is called on adopts a state (`fulfillment` or `rejection`) for which `then` has no handler, a new `Promise` is created with no additional handlers, simply adopting the final state of the original `Promise` on which `then` was called.

<strong>Syntax</strong><br/>
![eCCKAJ.png](https://s2.ax1x.com/2019/07/21/eCCKAJ.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>onFulfilled</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A <strong>Function</strong> called if the <strong>Promise</strong> is fulfilled. This function has one argument, the <strong>fulfillment value</strong>. If it is not a function, it is internally replaced with an "Identity" function (it returns the received argument).<br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>onRejected</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Optional<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A <strong>Function</strong> called if the <strong>Promise</strong> is rejected. This function has one argument, the <strong>rejection reason</strong>. If it is not a function, it is internally replaced with a "Thrower" function (it throws an error it received as argument).<br/>

&nbsp;&nbsp;<strong>Return value</strong><br/>
Once a Promise is fulfilled or rejected, the respective handler function (onFulfilled or onRejected) will be called asynchronously (scheduled in the current thread loop). The behavior of the handler function follows a specific set of rules. If a handler function:<br/>
&nbsp;&nbsp;- returns a value, the promise returned by `then` gets resolved with the returned value as its value;<br/>
&nbsp;&nbsp;- doesn't return anything, the promise returned by `then` gets resolved with an undefined value;<br/>
&nbsp;&nbsp;- throws an error, the promise returned by `then` gets rejected with the thrown error as its value;<br/>
&nbsp;&nbsp;- returns an already fulfilled promise, the promise returned by `then` gets fulfilled with that promise's value as its value;<br/>
&nbsp;&nbsp;- returns an already rejected promise, the promise returned by `then` gets rejected with that promise's value as its value;<br/>
&nbsp;&nbsp;- returns another pending promise object, the resolution/rejection of the promise returned by `then` will be subsequent to the resolution/rejection of the promise returned by the handler. Also, the value of the promise returned by `then` will be the same as the value of the promise returned by the handler.

Following, an example to demonstrate the asynchronicity of the `then` method.
![eCPVPA.png](https://s2.ax1x.com/2019/07/21/eCPVPA.png)
![eCPZ8I.png](https://s2.ax1x.com/2019/07/21/eCPZ8I.png)

<strong>Description</strong><br/>
As the <strong>then</strong> and <strong>Promise.prototype.catch()</strong> methods return promises, they can be chained — an operation called <ins>composition</ins>.

<strong>Examples</strong><br/>
&nbsp;&nbsp;<strong>Using the then method</strong><br/>
![eCPtx0.png](https://s2.ax1x.com/2019/07/21/eCPtx0.png)

&nbsp;&nbsp;<strong>Chaining</strong><br/>
The <strong>then</strong> method returns a <strong>Promise</strong> which allows for method chaining.

If the function passed as handler to <strong>then</strong> returns a <strong>Promise</strong>, an equivalent <strong>Promise</strong> will be exposed to the subsequent <strong>then</strong> in the method chain. The below snippet simulates asynchronous code with the <strong>setTimeout</strong> function.
![eCivX6.png](https://s2.ax1x.com/2019/07/21/eCivX6.png)
![eCiznK.png](https://s2.ax1x.com/2019/07/21/eCiznK.png)

When a value is simply returned from within a <strong>then</strong> handler, it will effectively return <strong>Promise.resolve(<value returned by whichever handler was called>)</strong>.
![eCFS0O.png](https://s2.ax1x.com/2019/07/21/eCFS0O.png)

A <strong>then</strong> call will return a rejected promise if the function throws an error or returns a rejected Promise.
![eCFA1I.png](https://s2.ax1x.com/2019/07/21/eCFA1I.png)

In all other cases, a resolving Promise is returned. In the following example, the first <strong>then()</strong> will return <strong>42</strong> wrapped resolving Promise even though the previous Promise in the chain was rejected.
![eCF6u6.png](https://s2.ax1x.com/2019/07/21/eCF6u6.png)

In practice, it is often desirable to catch rejected promises rather than use <strong>then</strong>'s two case syntax, as demonstrated below.
![eCFLVS.png](https://s2.ax1x.com/2019/07/21/eCFLVS.png)

You can also use chaining to implement one function with a Promise-based API on top of another such function.
![eCkuKx.png](https://s2.ax1x.com/2019/07/21/eCkuKx.png)

If <strong>onFulfilled</strong> returns a promise, the return value of <strong>then</strong> will be resolved/rejected by the promise.
![eCkRs0.png](https://s2.ax1x.com/2019/07/21/eCkRs0.png)
![eCk4dU.png](https://s2.ax1x.com/2019/07/21/eCk4dU.png)
![eCkqQ1.png](https://s2.ax1x.com/2019/07/21/eCkqQ1.png)

###### Promise.prototype.finally()
The <strong>finally()</strong> method returns a <strong>Promise</strong>. When the promise is settled, i.e either fulfilled or rejected, the specified callback function is executed. This provides a way for code to be run whether the promise was fulfilled successfully or rejected once the <strong>Promise</strong> has been dealt with.

This helps to avoid duplicating code in both the promise's <strong>then()</strong> and <strong>catch()</strong> handlers.

<strong>Syntax</strong><br/>
![eCAnYQ.png](https://s2.ax1x.com/2019/07/21/eCAnYQ.png)

&nbsp;&nbsp;<strong>Parameters</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<strong>onFinally</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A <strong>Function</strong> called when the <strong>Promise</strong> is settled.<br/>

&nbsp;&nbsp;<strong>Return value</strong><br/>
&nbsp;&nbsp;&nbsp;&nbsp;Returns a <strong>Promise</strong> whose <strong>finally</strong> handler is set to the specified function, <strong>onFinally</strong>.<br/>

<strong>Description</strong><br/>
The <strong>finally()</strong> method can be useful if you want to do some processing or cleanup once the promise is settled, regardless of its outcome.

The <strong>finally()</strong> method is very similar to calling <strong>.then(onFinally, onFinally)</strong> however there are a couple of differences:

- When creating a function inline, you can pass it once, instead of being forced to either declare it twice, or create a variable for it
- A <strong>finally</strong> callback will not receive any argument, since there's no reliable means of determining if the promise was fulfilled or rejected. This use case is for precisely when you do not care about the rejection reason, or the fulfillment value, and so there's no need to provide it.
- Unlike <strong>Promise.resolve(2).then(() => {}, () => {})</strong> (which will be resolved with <strong>undefined</strong>), <strong>Promise.resolve(2).finally(() => {})</strong> will be resolved with <strong>2</strong>.
- Similarly, unlike <strong>Promise.reject(3).then(() => {}, () => {})</strong> (which will be fulfilled with <strong>undefined</strong>), <strong>Promise.reject(3).finally(() => {})</strong> will be rejected with <strong>3</strong>.
> A `throw` (or returning a rejected promise) in the `finally` callback will reject the new promise with the rejection reason specified when calling `throw()`.

<strong>Examples</strong><br/>
![eCEp7T.png](https://s2.ax1x.com/2019/07/21/eCEp7T.png)

## Create a Promise
A Promise object is created using the new keyword and its constructor. This constructor takes as its argument a function, called the "executor function". This function should take two functions as parameters. The first of these functions (resolve) is called when the asynchronous task completes successfully and returns the results of the task as a value. The second (reject) is called when the task fails, and returns the reason for failure, which is typically an error object.
![e9nIsA.png](https://s2.ax1x.com/2019/07/21/e9nIsA.png)
To provide a function with promise functionality, simply have it return a promise:
![e9n7Zt.png](https://s2.ax1x.com/2019/07/21/e9n7Zt.png)

## Examples
#### Basic Example
![e9MQ2D.png](https://s2.ax1x.com/2019/07/21/e9MQ2D.png)
